export const SET_MOVIES = "SET_MOVIES";
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const SET_CINEMAWORLDMOVIE = 'SET_CINEMAWORLDMOVIE';
export const SET_FILMWORLDMOVIE = 'SET_FILMWORLDMOVIE';